import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {ReactQueryClientProvider} from "@/app/_components/ReactQueryClientProvider";
import {NUIProvider} from "@/providers/NextUIProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ReactQueryClientProvider>
                <body className={inter.className}>
                    <NUIProvider>
                        {children}
                    </NUIProvider>
                </body>
            </ReactQueryClientProvider>
        </html>
    );
}
